### ISSUE TITLE
Option to only activate if font tag is present

### ISSUE THREAD

**Issue by ghost** [nkokhelox/vscode-svg-font-previewer#20]
Per title. Is this possible with the VSC Extension API?

Basically a compatibility mode with the SVG preview in [lishu/vscode-svg2](https://github.com/lishu/vscode-svg2)

**Comment by 4086606** [comment]
Basically a compatibility mode with the SVG preview in [lishu/vscode-svg2](https://github.com/lishu/vscode-svg2)

**Comment by nkokhelox** [comment]
A new version v2 has been built. please check if this issue has been resolved for you.
