### ISSUE TITLE
rendering is closing single-line fonts

### ISSUE THREAD

**Issue by mark-hahn** [nkokhelox/vscode-svg-font-previewer#21]
This is an unclosed glyph from a straight-line font.  You can see it is a single non-closing curve.

```
<glyph unicode=")" glyph-name=")" 
    d="M 50 760 C 232.4 654.34 257.4 58.96 51.43 -69.29" 
    horiz-adv-x="229.98"
/>
```
But when rendering it shows as a closed curve with a filled-in area instead of just a line.  

![Screenshot (992)](https://user-images.githubusercontent.com/811455/157392635-114ce390-eeeb-410e-87a1-0cb598652630.png)

Am I missing some option or doing something wrong?

**Comment by nkokhelox** [comment]
Hey @mark-hahn thanks for reporting an issue, I'll have a look at it. If you've spotted where the error occurs, then the MR is more than welcome.

**Comment by nkokhelox** [comment]
@mark-hahn I have made 2 discoveries from this issue:
1. It seems like The SVG paths are assumed to be filled as a default behaviour.
 - to not fill the drawn path automatically, then the fill & the stroke attributes should be specified.
 2. This VSCode extension doesn't have support for those attributes yet.
 - I'll add the support for a glyph that specifies the `fill=none`

**Comment by mark-hahn** [comment]
A single-stroke font has no attributes like fill.  They are used in applications like cnc or fabric stitching where there is no prescribed line width.

**Comment by nkokhelox** [comment]
Hi @mark-hahn.
I've made a new release to cater for your needs: https://marketplace.visualstudio.com/items?itemName=nkokhelox.svg-font-previewer

You'd need to go to the extension setting and choose `stroke` as a renderer.

I hope this update timing is still relevant to you and thank you for pointing this issue out.

<img width="534" alt="Screenshot 2022-05-27 at 14 37 10" src="https://user-images.githubusercontent.com/10595966/170700682-946644b6-877e-482b-8fe4-b43aec3791e9.png">
